from __future__ import annotations

import math
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from typing import Any

import yfinance as yf
from fastapi import APIRouter, HTTPException, Query


# =====================================================================
# ROUTER
# =====================================================================

router = APIRouter(
    prefix="/api/market",
    tags=["Market Data"],
)


# =====================================================================
# CONFIGURATION
# =====================================================================

CACHE_TTL_SECONDS = 20

HISTORY_PERIOD = "5d"
HISTORY_INTERVAL = "1d"

YFINANCE_TIMEOUT_SECONDS = 15

# Number of market requests that may run concurrently for the
# Dashboard snapshot.
SNAPSHOT_MAX_WORKERS = 8

# The cache is deliberately process-local.
# This is suitable for the current single-process development setup.
_CACHE: dict[str, tuple[float, dict[str, Any]]] = {}

_CACHE_LOCK = threading.Lock()


# =====================================================================
# COMPANY NAMES
# =====================================================================

COMPANY_NAMES: dict[str, str] = {
    "ADANIENT": "Adani Enterprises",
    "ADANIPORTS": "Adani Ports",
    "APOLLOHOSP": "Apollo Hospitals",
    "ASIANPAINT": "Asian Paints",
    "AXISBANK": "Axis Bank",
    "BAJAJ-AUTO": "Bajaj Auto",
    "BAJAJFINSV": "Bajaj Finserv",
    "BAJFINANCE": "Bajaj Finance",
    "BEL": "Bharat Electronics",
    "BHARTIARTL": "Bharti Airtel",
    "CIPLA": "Cipla",
    "COALINDIA": "Coal India",
    "DRREDDY": "Dr. Reddy's Laboratories",
    "EICHERMOT": "Eicher Motors",
    "ETERNAL": "Eternal",
    "GRASIM": "Grasim Industries",
    "HCLTECH": "HCL Technologies",
    "HDFCBANK": "HDFC Bank",
    "HDFCLIFE": "HDFC Life Insurance",
    "HEROMOTOCO": "Hero MotoCorp",
    "HINDALCO": "Hindalco Industries",
    "HINDUNILVR": "Hindustan Unilever",
    "ICICIBANK": "ICICI Bank",
    "INDUSINDBK": "IndusInd Bank",
    "INFY": "Infosys",
    "ITC": "ITC",
    "JIOFIN": "Jio Financial Services",
    "JSWSTEEL": "JSW Steel",
    "KOTAKBANK": "Kotak Mahindra Bank",
    "LT": "Larsen & Toubro",
    "M&M": "Mahindra & Mahindra",
    "MARUTI": "Maruti Suzuki",
    "NESTLEIND": "Nestlé India",
    "NTPC": "NTPC",
    "ONGC": "ONGC",
    "POWERGRID": "Power Grid Corporation",
    "RELIANCE": "Reliance Industries",
    "SBILIFE": "SBI Life Insurance",
    "SBIN": "State Bank of India",
    "SHRIRAMFIN": "Shriram Finance",
    "SUNPHARMA": "Sun Pharmaceutical",
    "TATACONSUM": "Tata Consumer Products",
    "TATASTEEL": "Tata Steel",
    "TCS": "Tata Consultancy Services",
    "TECHM": "Tech Mahindra",
    "TITAN": "Titan Company",
    "TRENT": "Trent",
    "ULTRACEMCO": "UltraTech Cement",
    "WIPRO": "Wipro",
}


# =====================================================================
# MONITORED PORTFOLIO UNIVERSE
# =====================================================================

# These are the 49 stocks used by the QuantRisk AI model universe.
#
# IMPORTANT:
# These are application symbols.
# Yahoo Finance NSE symbols are generated by adding ".NS".
#
# Example:
#   WIPRO     -> WIPRO.NS
#   RELIANCE  -> RELIANCE.NS
#   M&M       -> M&M.NS

MONITORED_SYMBOLS = [
    "ADANIENT",
    "ADANIPORTS",
    "APOLLOHOSP",
    "ASIANPAINT",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJAJFINSV",
    "BAJFINANCE",
    "BEL",
    "BHARTIARTL",
    "CIPLA",
    "COALINDIA",
    "DRREDDY",
    "EICHERMOT",
    "GRASIM",
    "HCLTECH",
    "HDFCBANK",
    "HDFCLIFE",
    "HEROMOTOCO",
    "HINDALCO",
    "HINDUNILVR",
    "ICICIBANK",
    "INDUSINDBK",
    "INFY",
    "ITC",
    "JSWSTEEL",
    "KOTAKBANK",
    "LT",
    "M&M",
    "MARUTI",
    "NESTLEIND",
    "NTPC",
    "ONGC",
    "POWERGRID",
    "RELIANCE",
    "SBILIFE",
    "SBIN",
    "SHRIRAMFIN",
    "SUNPHARMA",
    "TATACONSUM",
    "TATASTEEL",
    "TCS",
    "TECHM",
    "TITAN",
    "TRENT",
    "ULTRACEMCO",
    "WIPRO",
    "ETERNAL",
    "JIOFIN",
]


# Keep the original default symbols for compatibility with any
# existing code that imports/uses DEFAULT_SYMBOLS.
DEFAULT_SYMBOLS = [
    "RELIANCE.NS",
    "TCS.NS",
    "INFY.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
]


# =====================================================================
# NUMERIC HELPERS
# =====================================================================

def clean_number(value: Any) -> float | None:
    """
    Convert a value into a JSON-safe finite float.

    Returns:
        float  -> valid finite number
        None   -> missing/invalid/NaN/infinite value
    """

    if value is None:
        return None

    try:
        number = float(value)

    except (TypeError, ValueError):
        return None

    if not math.isfinite(number):
        return None

    return number


def clean_integer(value: Any) -> int | None:
    """
    Convert a numeric value into a safe integer.

    Used primarily for volume.
    """

    number = clean_number(value)

    if number is None:
        return None

    try:
        return int(number)

    except (TypeError, ValueError, OverflowError):
        return None


# =====================================================================
# SYMBOL HELPERS
# =====================================================================

def normalize_symbol(symbol: str) -> str:
    """
    Convert an application stock symbol into an NSE Yahoo symbol.

    Examples:

        WIPRO
            -> WIPRO.NS

        WIPRO.NS
            -> WIPRO.NS

        tcs
            -> TCS.NS

        RELIANCE.NS
            -> RELIANCE.NS
    """

    cleaned = str(symbol or "").strip().upper()

    if not cleaned:
        raise HTTPException(
            status_code=400,
            detail="Stock symbol is required.",
        )

    cleaned = cleaned.strip()

    # Yahoo NSE symbols use .NS.
    if not cleaned.endswith(".NS"):
        cleaned = f"{cleaned}.NS"

    # Avoid malformed symbols such as:
    # ABC.NS.NS
    while cleaned.endswith(".NS.NS"):
        cleaned = cleaned[:-3]

    return cleaned


def display_symbol(symbol: str) -> str:
    """
    Convert a Yahoo NSE symbol into the application's display symbol.

    Example:

        WIPRO.NS -> WIPRO
    """

    normalized = normalize_symbol(symbol)

    return normalized[:-3]


def get_company_name(symbol: str) -> str:
    """
    Return a known company name or fall back to the display symbol.
    """

    base_symbol = display_symbol(symbol)

    return COMPANY_NAMES.get(
        base_symbol,
        base_symbol,
    )


# =====================================================================
# CACHE HELPERS
# =====================================================================

def get_cached_quote(
    symbol: str,
) -> dict[str, Any] | None:
    """
    Return a cached quote if it is still within the TTL.
    """

    now = time.monotonic()

    with _CACHE_LOCK:
        cached = _CACHE.get(symbol)

        if cached is None:
            return None

        cached_at, payload = cached

        if (
            now - cached_at
            >= CACHE_TTL_SECONDS
        ):
            _CACHE.pop(
                symbol,
                None,
            )

            return None

        # Return a copy so callers cannot mutate
        # the cached dictionary accidentally.
        return dict(payload)


def set_cached_quote(
    symbol: str,
    payload: dict[str, Any],
) -> None:
    """
    Store a quote in the local cache.
    """

    with _CACHE_LOCK:
        _CACHE[symbol] = (
            time.monotonic(),
            dict(payload),
        )


def clear_market_cache() -> None:
    """
    Clear all cached market quotes.

    Kept as a helper for development/testing.
    """

    with _CACHE_LOCK:
        _CACHE.clear()


# =====================================================================
# HISTORY
# =====================================================================

def get_latest_history(
    ticker: yf.Ticker,
):
    """
    Retrieve recent daily market observations.

    IMPORTANT:
        This is latest available daily market data from yfinance.
        It is not an official NSE real-time exchange feed.
    """

    try:
        history = ticker.history(
            period=HISTORY_PERIOD,
            interval=HISTORY_INTERVAL,
            auto_adjust=False,
            actions=False,
            repair=True,
            timeout=YFINANCE_TIMEOUT_SECONDS,
        )

    except Exception as exc:
        raise HTTPException(
            status_code=502,
            detail=(
                "Unable to retrieve market data "
                "from the configured provider."
            ),
        ) from exc

    if history is None or history.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                "No market data was returned "
                "for this symbol."
            ),
        )

    if "Close" not in history.columns:
        raise HTTPException(
            status_code=502,
            detail=(
                "Market data response does not "
                "contain a Close price."
            ),
        )

    history = history.dropna(
        subset=["Close"],
        how="all",
    )

    if history.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                "No valid market price was "
                "returned for this symbol."
            ),
        )

    latest = history.iloc[-1]

    previous = None

    if len(history) >= 2:
        previous = history.iloc[-2]

    return (
        history,
        latest,
        previous,
    )


# =====================================================================
# DATE/TIME
# =====================================================================

def serialize_market_date(
    history: Any,
) -> str | None:
    """
    Convert the latest historical index into an ISO string.
    """

    try:
        market_date = history.index[-1]

        if hasattr(
            market_date,
            "to_pydatetime",
        ):
            market_date = (
                market_date.to_pydatetime()
            )

        if isinstance(
            market_date,
            datetime,
        ):
            return market_date.isoformat()

        return str(market_date)

    except Exception:
        return None


def current_timestamp() -> str:
    """
    Return the current timezone-aware local timestamp.
    """

    return (
        datetime.now()
        .astimezone()
        .isoformat()
    )


# =====================================================================
# QUOTE BUILDER
# =====================================================================

def build_quote(
    symbol: str,
) -> dict[str, Any]:
    """
    Retrieve and normalize the latest available market quote.

    This is the single source of truth used by the quote routes
    and the Dashboard snapshot route.
    """

    requested_symbol = (
        str(symbol or "")
        .strip()
        .upper()
    )

    if not requested_symbol:
        raise HTTPException(
            status_code=400,
            detail="Stock symbol is required.",
        )

    yahoo_symbol = normalize_symbol(
        requested_symbol
    )

    # ---------------------------------------------------------------
    # CACHE
    # ---------------------------------------------------------------

    cached = get_cached_quote(
        yahoo_symbol
    )

    if cached is not None:
        cached["cached"] = True

        return cached

    # ---------------------------------------------------------------
    # PROVIDER
    # ---------------------------------------------------------------

    try:
        ticker = yf.Ticker(
            yahoo_symbol
        )

        (
            history,
            latest,
            previous,
        ) = get_latest_history(
            ticker
        )

    except HTTPException:
        raise

    except Exception as exc:
        raise HTTPException(
            status_code=502,
            detail=(
                "Market data provider "
                "error."
            ),
        ) from exc

    # ---------------------------------------------------------------
    # LATEST VALUES
    # ---------------------------------------------------------------

    close = clean_number(
        latest.get("Close")
    )

    open_price = clean_number(
        latest.get("Open")
    )

    high = clean_number(
        latest.get("High")
    )

    low = clean_number(
        latest.get("Low")
    )

    volume = clean_integer(
        latest.get("Volume")
    )

    if close is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Latest market price is "
                f"unavailable for "
                f"{requested_symbol}."
            ),
        )

    # ---------------------------------------------------------------
    # PREVIOUS CLOSE
    # ---------------------------------------------------------------

    previous_close = None

    if previous is not None:
        previous_close = clean_number(
            previous.get("Close")
        )

    # ---------------------------------------------------------------
    # CHANGE
    # ---------------------------------------------------------------

    change = None
    change_percent = None

    if (
        previous_close is not None
        and previous_close != 0
    ):
        change = (
            close
            - previous_close
        )

        change_percent = (
            change
            / previous_close
        ) * 100.0

    # ---------------------------------------------------------------
    # MARKET DATE
    # ---------------------------------------------------------------

    market_date = serialize_market_date(
        history
    )

    # ---------------------------------------------------------------
    # RESPONSE
    # ---------------------------------------------------------------

    payload: dict[str, Any] = {
        # Application symbol
        "symbol": display_symbol(
            yahoo_symbol
        ),

        # Yahoo symbol
        "yahoo_symbol": yahoo_symbol,

        # Company information
        "company": get_company_name(
            yahoo_symbol
        ),

        # Price information
        "price": close,
        "previous_close": previous_close,

        "change": clean_number(
            change
        ),

        "change_percent": clean_number(
            change_percent
        ),

        # OHLC
        "open": open_price,
        "high": high,
        "low": low,

        # Explicit aliases useful to UI components
        "day_high": high,
        "day_low": low,

        # Volume
        "volume": volume,

        # Market date
        "market_date": market_date,

        # Provider metadata
        "source": (
            "Yahoo Finance via yfinance"
        ),

        "source_type": (
            "market-data-provider"
        ),

        "provider": "yfinance",

        # This endpoint intentionally does not claim
        # to be an official exchange feed.
        "official_exchange_feed": False,

        "delayed_or_latest_available": True,

        # Current implementation uses daily observations.
        "interval": HISTORY_INTERVAL,

        "period": HISTORY_PERIOD,

        # Status
        "status": "ok",

        # Cache status
        "cached": False,

        # Retrieval timestamp
        "retrieved_at": current_timestamp(),
    }

    set_cached_quote(
        yahoo_symbol,
        payload,
    )

    return payload


# =====================================================================
# DASHBOARD SNAPSHOT HELPERS
# =====================================================================

def fetch_snapshot_quote(
    symbol: str,
) -> dict[str, Any] | None:
    """
    Fetch one monitored stock for the Dashboard snapshot.

    A failure for one stock is intentionally isolated so that
    one unavailable provider response does not make all other
    valid market quotes disappear.
    """

    try:
        return build_quote(symbol)

    except HTTPException:
        return None

    except Exception:
        return None


# =====================================================================
# HEALTH CHECK
# =====================================================================

@router.get("/health")
def market_health() -> dict[str, Any]:
    """
    Verify that the market router is registered.
    """

    return {
        "status": "ok",
        "service": "market-data",
        "provider": (
            "Yahoo Finance via yfinance"
        ),
        "interval": HISTORY_INTERVAL,
        "period": HISTORY_PERIOD,
        "official_exchange_feed": False,
        "cache_ttl_seconds": (
            CACHE_TTL_SECONDS
        ),
        "monitored_symbols": len(
            MONITORED_SYMBOLS
        ),
    }


# =====================================================================
# DASHBOARD MARKET SNAPSHOT
# =====================================================================

@router.get("/snapshot")
def market_snapshot(
    refresh: bool = Query(
        False,
        description=(
            "Clear the local market cache "
            "before retrieving the snapshot."
        ),
    ),
) -> dict[str, Any]:
    """
    Return the latest available market information for
    the complete QuantRisk AI monitored universe.

    This endpoint is used by Dashboard.jsx.

    The Dashboard expects:

        /api/market/snapshot

    The response contains:

        status
        updated_at
        requested_symbols
        available_symbols
        advancing
        declining
        unchanged
        quotes

    No artificial market values are generated.
    """

    # ---------------------------------------------------------------
    # OPTIONAL FORCE REFRESH
    # ---------------------------------------------------------------

    if refresh:
        clear_market_cache()

    # ---------------------------------------------------------------
    # FETCH ALL 49 SYMBOLS
    # ---------------------------------------------------------------

    successful_quotes: list[dict[str, Any]] = []

    with ThreadPoolExecutor(
        max_workers=SNAPSHOT_MAX_WORKERS
    ) as executor:

        futures = {
            executor.submit(
                fetch_snapshot_quote,
                symbol,
            ): symbol
            for symbol in MONITORED_SYMBOLS
        }

        for future in as_completed(futures):

            try:
                quote = future.result()

            except Exception:
                quote = None

            if quote is not None:
                successful_quotes.append(
                    quote
                )

    # ---------------------------------------------------------------
    # STABLE ORDER
    # ---------------------------------------------------------------

    # Thread completion order is not deterministic.
    # Reorder the valid results according to the
    # monitored portfolio universe.
    order = {
        symbol: index
        for index, symbol
        in enumerate(
            MONITORED_SYMBOLS
        )
    }

    successful_quotes.sort(
        key=lambda quote: order.get(
            quote.get("symbol"),
            len(MONITORED_SYMBOLS),
        )
    )

    # ---------------------------------------------------------------
    # MARKET MOVEMENT COUNTS
    # ---------------------------------------------------------------

    advancing = 0
    declining = 0
    unchanged = 0

    for quote in successful_quotes:

        change = clean_number(
            quote.get("change")
        )

        if change is None:
            continue

        if change > 0:
            advancing += 1

        elif change < 0:
            declining += 1

        else:
            unchanged += 1

    # ---------------------------------------------------------------
    # STATUS
    # ---------------------------------------------------------------

    requested_count = len(
        MONITORED_SYMBOLS
    )

    available_count = len(
        successful_quotes
    )

    if available_count == requested_count:
        status = "available"

    elif available_count > 0:
        status = "partial"

    else:
        status = "unavailable"

    # ---------------------------------------------------------------
    # RESPONSE
    # ---------------------------------------------------------------

    return {
        "status": status,

        "updated_at": current_timestamp(),

        "requested_symbols": requested_count,

        "available_symbols": available_count,

        "advancing": advancing,

        "declining": declining,

        "unchanged": unchanged,

        "quotes": successful_quotes,

        # Provider information
        "source": (
            "Yahoo Finance via yfinance"
        ),

        "provider": "yfinance",

        "official_exchange_feed": False,

        "delayed_or_latest_available": True,

        "interval": HISTORY_INTERVAL,

        "period": HISTORY_PERIOD,

        # Development/cache information
        "cache_ttl_seconds": (
            CACHE_TTL_SECONDS
        ),

        "refresh_requested": refresh,
    }


# =====================================================================
# QUERY-STRING QUOTE ROUTE
# =====================================================================

@router.get("/quote")
def market_quote(
    symbol: str = Query(
        ...,
        min_length=1,
        description=(
            "NSE stock symbol, for example "
            "WIPRO, TCS or RELIANCE."
        ),
    ),
) -> dict[str, Any]:
    """
    Query-string quote endpoint.

    Examples:

        /api/market/quote?symbol=WIPRO

        /api/market/quote?symbol=TCS

        /api/market/quote?symbol=RELIANCE

        /api/market/quote?symbol=WIPRO.NS
    """

    return build_quote(symbol)


# =====================================================================
# PATH-BASED COMPATIBILITY ROUTE
# =====================================================================

@router.get("/quote/{symbol:path}")
def market_quote_by_symbol(
    symbol: str,
) -> dict[str, Any]:
    """
    Path-based compatibility endpoint.

    Examples:

        /api/market/quote/WIPRO

        /api/market/quote/TCS

        /api/market/quote/RELIANCE

        /api/market/quote/WIPRO.NS
    """

    return build_quote(symbol)


# =====================================================================
# CACHE CLEAR
# =====================================================================

@router.post("/cache/clear")
def clear_market_cache_route() -> dict[str, Any]:
    """
    Clear the process-local market quote cache.

    Useful during development when testing fresh responses.
    """

    clear_market_cache()

    return {
        "status": "ok",
        "message": (
            "Market quote cache cleared."
        ),
    }